=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/activity.dtd
<!ELEMENT activity ( meta, client-cfg, server-cfg ) >
<!ATTLIST activity enabled NMTOKEN #REQUIRED >
<!ATTLIST activity version NMTOKEN #REQUIRED >
<!ELEMENT author ( #PCDATA ) >
<!ELEMENT client-cfg ( entry+ ) >
<!ELEMENT entry EMPTY >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry overridable (yes|no) "yes" >
<!ATTLIST entry value CDATA #REQUIRED >
<!ELEMENT meta ( name, author+ ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT pipeline EMPTY >
<!ATTLIST pipeline desc CDATA #REQUIRED >
<!ELEMENT post ( pipeline, entry* ) >
<!ELEMENT pre ( pipeline, entry* ) >
<!ELEMENT server-cfg ( lang+ ) >
<!ELEMENT lang ( pre, post ) >
<!ATTLIST lang code NMTOKEN #REQUIRED >

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/Konjunktiv/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="no">
	<meta>
		<name>Konjunktiv II</name>
		<author>Adriane Boyd</author>
	</meta>
		<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="de">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/Konjunktiv.xml"/>
			</pre>
		</lang>
	</server-cfg>
</activity>
