=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/activity.dtd
<!ELEMENT activity ( meta, client-cfg, server-cfg ) >
<!ATTLIST activity enabled NMTOKEN #REQUIRED >
<!ATTLIST activity version NMTOKEN #REQUIRED >
<!ELEMENT author ( #PCDATA ) >
<!ELEMENT client-cfg ( entry+ ) >
<!ELEMENT entry EMPTY >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry overridable (yes|no) "yes" >
<!ATTLIST entry value CDATA #REQUIRED >
<!ELEMENT meta ( name, author+ ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT pipeline EMPTY >
<!ATTLIST pipeline desc CDATA #REQUIRED >
<!ELEMENT post ( pipeline, entry* ) >
<!ELEMENT pre ( pipeline, entry* ) >
<!ELEMENT server-cfg ( lang+ ) >
<!ELEMENT lang ( pre, post ) >
<!ATTLIST lang code NMTOKEN #REQUIRED >

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/SerEstar/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Ser vs. Estar</name>
		<author>Adriane Boyd</author>
	</meta>
	<client-cfg />
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="es">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/TreeTagger-SerEstar.xml"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/RusNounSingular/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Russian Noun Singular (beta)</name>
		<author>Adriane Boyd, Heli Uibo, Eduard Schaf</author>
	</meta>
	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
	<!-- the client-cfg is in js-lib for newer releases, f ex WERTiCore -->
	   		<!-- the enhancement style for a colorize activity: -->
		<entry key="colorizeStyle" value="color: #22F; font-weight:bold" overridable="yes"/>
		<!-- this is the default style for the input box in a cloze activity: -->
		<entry key="clozeDefaultStyle" value="font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box in a cloze activity is set to this style if the input was wrong: -->
		<entry key="clozeWrongStyle" value="color: red; font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box is replaced by a text of this style if the input was correct: -->
		<entry key="clozeCorrectStyle" value="color: green; font-weight:bold" overridable="yes"/>
		<!-- show hint questionmarks in cloze activity? if so, define their style... -->
		<entry key="clozeShowHints" value="yes" overridable="yes" />
		<entry key="clozeHintStyle" value="font-weight:regular; width:15px; border:1px solid #A0A0A0; background:#E9E9E9; color:#A0A0A0; margin-left:2px;" overridable="yes"/>
		<entry key="clozeHintSolvedStyle" value="color: #22F; font-weight:bold" overridable="yes"/>

	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="ru">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislcg3RusNounSingularPipe.xml"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/Gerunds/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Gerunds vs. Infinitives</name>
		<author>Niels Ott</author>
		<author>Ramon Ziai</author>
	</meta>	
	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
		<!-- enhancement styles for the colorize activity -->
		<entry key="enhancementStyleGER" value="color: #ce6006; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleINF" value="color: #8c01c0; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_GERONLY" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_INFONLY" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_BOTHMEANSAME" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_BOTHMEANDIFF" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_FIXEDEXP" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<!-- this is the default style for the input box in a cloze activity: -->
		<entry key="clozeDefaultStyle" value="font-weight:bold; width:75px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box in a cloze activity is set to this style if the input was wrong: -->
		<entry key="clozeWrongStyle" value="color: red; font-weight:bold; width:75px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box is replaced by a text of this style if the input was correct: -->
		<entry key="clozeCorrectStyle" value="color: green; font-weight:bold" overridable="yes"/>
		<!-- show hint questionmarks in cloze activity? if so, define their style... -->
		<entry key="clozeShowHints" value="yes" overridable="yes" />
		<entry key="clozeHintStyle" value="font-weight:regular; width:15px; border:1px solid #A0A0A0; background:#E9E9E9; color:#A0A0A0; margin-left:2px;" overridable="yes"/>
		<entry key="clozeHintSolvedStyle" value="color: #22F; font-weight:bold" overridable="yes"/>
	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislcg3Pipe.xml"/>
				<entry key="vislcg3Loc" value="/usr/local/werti/bin/vislcg3" overridable="no"/>
				<!-- relative paths should be interpreted as relative to the respective activity directory -->
				<entry key="vislcg3GrammarLoc" value="_ACT_/resources/gerundsgrammar" overridable="no"/>
                <entry key="vislCGPostProc_chunkTags" value="INF,GER,CLU-GERONLY,CLU-INFONLY,CLU-BOTHMEANSAME,CLU-BOTHMEANDIFF,CLU-FIXEDEXP,PRO,PAR,GOI,GOP,AMB,RELEVANT" overridable="no"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/Passives/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="no">
	<meta>
		<name>Passives</name>
		<author>Adriane Boyd</author>
	</meta>
		<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/Passives.xml"/>
			</pre>
			<post>
				<pipeline desc="/operators/PassivesPost.xml"/>
			</post>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/Arts/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Articles</name>
		<author>Adriane Boyd</author>
	</meta>

	<client-cfg></client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre lang="en">
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/OpenNlpTokenizerPipe.xml"/>
                <entry key="WordEnhancer_Words" value="a,an,the" overridable="yes"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/WhQuestions/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Wh-Questions</name>
		<author>Iliana Simova</author>
	</meta>	
	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
		<!-- enhancement styles for the colorize activity -->
		<entry key="enhancementStyleSVI" value="background-color: #E6E6FA; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleSVO" value="background-color: #FAEBD7; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleWH" value="color: #0000FF; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleWHS" value="color: #1E90FF; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleAUX" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleMVERB" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleSUBJ" value="color: #808000; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleNFIN" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/TreeTagger.xml"/>
				<entry key="vislcg3Loc" value="/usr/local/werti/bin/vislcg3" overridable="no"/>
				<!-- relative paths should be interpreted as relative to the respective activity directory -->
				<entry key="vislcg3GrammarLoc" value="_ACT_/resources/whgram" overridable="no"/>
                <!-- <entry key="vislCGPostProc-2_Tags" value="lala,troet" overridable="no"/> -->
                <entry key="vislCGPostProc-2_chunkTags" value="WHS,WH,SUBJ,AUX,MVERB,NFIN,SVI,SVO,Q" overridable="no"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/PhrasalVerbs/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Phrasal Verbs</name>
		<author>Adriane Boyd</author>
	</meta>
		<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
		<!-- enhancement styles for the colorize activity -->
		<entry key="enhancementStyleSVI" value="background-color: #E6E6FA; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleSVO" value="background-color: #FAEBD7; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleWH" value="color: #0000FF; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleWHS" value="color: #1E90FF; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleAUX" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleMVERB" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleSUBJ" value="color: #808000; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleNFIN" value="color: #FF4500; font-weight:bold" overridable="yes"/>
		</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/PhrasalVerbs.xml"/>
			</pre>
		</lang>
	</server-cfg>
</activity>

=== reynoldsnlp/legacyVIEW/src/main/webapp/activities/NounCountability/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Noun Countability</name>
		<author>Adriane Boyd</author>
	</meta>	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/OpenNlpChunkerPipe.xml"/>
				<!--  <entry key="port" value="7000" overridable="no"/>
				<entry key="featureExtractor" value="werti.ml.fe.NounCountabilityFeatureExtractor" overridable="no"/>
				<entry key="sparseFeatures" value="false" overridable="no"/>
				<entry key="featureSeparator" value="," overridable="no"/>
				<entry key="posFilter" value="^NNS?$" overridable="no"/> -->
                <entry key="NounCountEnhancer_tags" value="COUNT,NONCOUNT,BOTH" overridable="no"/>
                <entry key="NounCountEnhancer_countFile" value="_ACT_/resources/count.txt" overridable="no"/>
                <entry key="NounCountEnhancer_noncountFile" value="_ACT_/resources/noncount.txt" overridable="no"/>
                <entry key="NounCountEnhancer_bothFile" value="_ACT_/resources/both.txt" overridable="no"/>
                <entry key="NounCountEnhancer_posFilter" value="^NNS?$" overridable="no"/>
			</pre>
		</lang>
	</server-cfg>
</activity>
